### ISSUE TITLE
Issue with juliaconsole with Julia 1.0

### ISSUE THREAD

**Issue by tawheeler** [gpoore/pythontex#131]
I updated to 0.17dev and started using Julia 1. I now have the following issue:

```
This is PythonTeX 0.17dev
Traceback (most recent call last):
  File "/usr/local/texlive/2018/bin/x86_64-linux/pythontex", line 62, in <module>
    pythontex.main()
  File "/usr/local/texlive/2018/texmf-dist/scripts/pythontex/pythontex2.py", line 2717, in main
    do_multiprocessing(data, temp_data, old_data, engine_dict)
  File "/usr/local/texlive/2018/texmf-dist/scripts/pythontex/pythontex2.py", line 1372, in do_multiprocessing
    result = task.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 2] No such file or directory: 'pythontex-files-optimization-chapter/juliacon_default_default.tex'
```

When using blocks such as 

```
\begin{juliaconsole}
using Distributions
N = Normal(0,1);
cdf(N, 1) - cdf(N, -1)
cdf(N, 1)
\end{juliaconsole}
```

**Comment by tawheeler** [comment]
All I needed to do to fix this was install Weave.jl.

**Comment by gpoore** [comment]
I've fixed the error handling so that if Weave.jl is missing or raises errors, you get the stderr from Julia instead of a cryptic message related to failed post-processing.

**Comment by tawheeler** [comment]
Awesome! Thanks
