### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by naiieandrade** [gpoore/pythontex#133]
Hello, I was looking for options to work with python in Latex, or something like that.
I found Pythontex, but I think will be good you improve your README, with "how to use", "examples", "operational systems". It's just a suggestion. 

I read the pdfs, but something simple and easy to see and read in README is always better. :grin:

**Comment by ortollj** [comment]
Hello
I agee with you Naiara
it's been over an hour now that I'm trying to figure out how to install pytontex on UBUNTU without success !

**Comment by gpoore** [comment]
@ortollj Have you tried installing `pythontex` with the TeX Live package manager? That's the best option. Perhaps something like `tlmgr install pythontex`?

Documentation in HTML form would definitely be nice. There is complete documentation, though, in [`pythontex.pdf`](https://github.com/gpoore/pythontex/blob/master/pythontex/pythontex.pdf), with a short summary in [`pythontex_quickstart.pdf`](https://github.com/gpoore/pythontex/blob/master/pythontex_quickstart/pythontex_quickstart.pdf) and examples in [`pythontex_gallery.pdf`](https://github.com/gpoore/pythontex/blob/master/pythontex_gallery/pythontex_gallery.pdf).

**Comment by ortollj** [comment]
is the package v017 for Windows or for Linux or both ?

**Comment by ortollj** [comment]
```
ortollj@ortollj-SATELLITE-C70-B:~$ sudo apt-get install xzdec
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  xzdec
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 55,7 kB of archives.
After this operation, 268 kB of additional disk space will be used.
Get:1 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 xzdec amd64 5.2.2-1.3 [55,7 kB]
Fetched 55,7 kB in 1s (42,3 kB/s)       
Selecting previously unselected package xzdec.
(Reading database ... 342994 files and directories currently installed.)
Preparing to unpack .../xzdec_5.2.2-1.3_amd64.deb ...
Unpacking xzdec (5.2.2-1.3) ...
Setting up xzdec (5.2.2-1.3) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
ortollj@ortollj-SATELLITE-C70-B:~$ tlmgr install framed
(running on Debian, switching to user mode!)
tlmgr: Remote repository is newer than local (2017 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
ortollj@ortollj-SATELLITE-C70-B:~$ tlmgr install pythontex
(running on Debian, switching to user mode!)
tlmgr: Remote repository is newer than local (2017 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
ortollj@ortollj-SATELLITE-C70-B:~$ 

```

**Comment by gpoore** [comment]
@ortollj It looks like your TeX Live is out of date (2017). You could install the latest version from the [TeX Live site](https://www.tug.org/texlive/). Otherwise, you won't be able to use the package manager, so you will have to install additional packages like `pythontex` via Ubuntu's package manager (I think there are several bundles of LaTeX packages, not sure which one might contain `pythontex`). That should work but may give you packages that are several years old. Or you could download the latest `pythontex` directly from GitHub and use the included Python installation script. That could work, though you may have issues with the other packages being so old.

**Comment by ortollj** [comment]
@gpoor it seems it is the latest Tex Live version installed ?

```
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ sudo apt-get install texlive-full
[sudo] password for ortollj: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
texlive-full is already the newest version (2017.20180305-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by ortollj** [comment]
could you precise me how to install the package pythontex ?
Sorry, but I can not understand how to do for UBUNTU

**Comment by ortollj** [comment]
```
ortollj@ortollj-SATELLITE-C70-B:~/Downloads/pythontex-master/pythontex$ latex pythontex.ins md ~/texmf md ~/texmf/tex mv * ~/texmf/tex chmod +x ~/texmf/
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./pythontex.ins
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/docstrip.tex
Utility: `docstrip' 2.5e <2014/09/29>
English documentation    <2017/03/13>

**********************************************************
* This program converts documented macro-files into fast *
* loadable files by stripping off (nearly) all comments! *
**********************************************************

********************************************************
* No Configuration file found, using default settings. *
********************************************************

) File ./pythontex.sty already exists on the system.
Overwrite it? [y/n]
\answer=y

Generating file(s) ./pythontex.sty 

Processing file pythontex.dtx (package) -> pythontex.sty
File pythontex.dtx ended by \endinput.
Lines  processed: 4788
Comments removed: 2934
Comments  passed: 1
Codelines passed: 1843

*************************************************************
*                                                           *
* To finish the installation you have to move the following *
* file into a directory searched by TeX:                    *
*                                                           *
*     pythontex.sty                                         *
*                                                           *
* To produce the documentation run the file pythontex.dtx   *
* through LaTeX.                                            *
*                                                           *
* Happy TeXing!                                             *
*                                                           *
*************************************************************
 )
No pages of output.
Transcript written on pythontex.log.
ortollj@ortollj-SATELLITE-C70-B:~/Downloads/pythontex-master/pythontex$ 

```

**Comment by gpoore** [comment]
@ortollj Your TeX Live is 2 years out of date, because Ubuntu is always somewhat behind. The TeX Live site has instructions for directly installing the current version, which is often the best approach.

For direct PythonTeX installation, download from https://github.com/gpoore/pythontex/releases, unzip, and run the installation script. For such an old version of TeX Live, it would be worth trying the latest release (0.17), but you may have to go with an older version due to all the other packages being so old.

**Comment by ortollj** [comment]
ok , I'm updating Tex Live, I will tell you

**Comment by ortollj** [comment]
could you tell me what is the 3 cmds to add the 3 path ?

Add /usr/local/texlive/2019/texmf-dist/doc/man to MANPATH.
Add /usr/local/texlive/2019/texmf-dist/doc/info to INFOPATH.
Most importantly, add /usr/local/texlive/2019/bin/x86_64-linux
to your PATH for current and future sessions.
Logfile: /usr/local/texlive/2019/install-tl.log

  ```
201  sudo apt autoremove bcmwl-kernel-source
  202  sudo apt-get install bcmwl-kernel-source
  203  sudo tlmgr install pythontex
  204  tlmgr update --all
  205  tlmgr init-usertree
  206  sudo apt-get install xzdec
  207  tlmgr install framed
  208  tlmgr install pythontex
  209  pwd
  210  cd Downloads/
  211  ls
  212  cd pythontex-master/
  213  ls
  214  cd pythontex
  215  latex pythontex.ins md ~/texmf md ~/texmf/tex mv * ~/texmf/tex chmod +x ~/texmf/
  216  cd Downloads/cd ..
  217  cd ..
  218  ls
  219  cd install-tl-20190927/
  220  ls
  221  ./install-tl
  222  sudo ./install-tl
  223  export PATH="/usr/local/texlive/2019/bin/x86_64-linux:$PATH"
  224  export PATH="/usr/local/texlive/2019/texmf-dist/doc/man:$MANPATH"
  225  export PATH="/usr/local/texlive/2019/texmf-dist/doc/info:$INFOPATH"
  226  history
ortollj@ortollj-SATELLITE-C70-B:~/Downloads/install-tl-20190927$ source ~/.bashrc
Command 'lesspipe' is available in the following places
 * /bin/lesspipe
 * /usr/bin/lesspipe
The command could not be located because '/usr/bin:/bin' is not included in the PATH environment variable.
lesspipe: command not found
Command 'dircolors' is available in '/usr/bin/dircolors'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
dircolors: command not found
```

**Comment by ortollj** [comment]
```
ortollj@ortollj-SATELLITE-C70-B:~/Downloads/install-tl-20190927$ echo $PATH
/home/ortollj/bin:/usr/local/bin/texlive/2019/bin/x86_64-linux:/home/ortollj/bin:/usr/local/bin/texlive/2019/bin/x86_64-linux:/home/ortollj/bin:~/usr/local/bin/texlive/2019/bin/x86_64-linux:/home/ortollj/bin:~/usr/local/texlive/2019/texmf-dist/doc/info:
ortollj@ortollj-SATELLITE-C70-B:~/Downloads/install-tl-20190927$ 
```

**Comment by ortollj** [comment]
still does not work

```
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ pdflatex hello.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./hello.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pythontex/pythontex.sty
(/usr/share/texlive/texmf-dist/tex/latex/fvextra/fvextra.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
)) (/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lineno/lineno.sty))
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)))) (/usr/share/texlive/texmf-dist/tex/latex/caption/newfloat.sty)
(/usr/share/texlive/texmf-dist/tex/latex/currfile/currfile.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/filehook/filehook.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./hello.aux
)
No file pythontex-files-hello/hello.pytxmcr.
Run PythonTeX to create it.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (./hello.aux) )
No pages of output.
Transcript written on hello.log.
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ 

```

**Comment by ortollj** [comment]
```
ortollj@ortollj-SATELLITE-C70-B:/usr/local/texlive/2019$ pwd
/usr/local/texlive/2019
ortollj@ortollj-SATELLITE-C70-B:/usr/local/texlive/2019$ ls
bin         install-tl      LICENSE.TL       readme-txt.dir       texmf.cnf     texmf-dist
doc.html    install-tl.log  README           README.usergroups    texmfcnf.lua  texmf-var
index.html  LICENSE.CTAN    readme-html.dir  release-texlive.txt  texmf-config  tlpkg
ortollj@ortollj-SATELLITE-C70-B:/usr/local/texlive/2019$ 
```

**Comment by gpoore** [comment]
@ortollj Following the documentation, try `pdflatex hello.tex && pythontex hello.tex && pdflatex hello.tex`. Just running LaTeX isn't enough, which is why the message says to run PythonTeX.

**Comment by ortollj** [comment]
```
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ pdflatex hello.tex && pythontex hello.tex && pdflatex hello.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./hello.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pythontex/pythontex.sty
(/usr/share/texlive/texmf-dist/tex/latex/fvextra/fvextra.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
)) (/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lineno/lineno.sty))
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)))) (/usr/share/texlive/texmf-dist/tex/latex/caption/newfloat.sty)
(/usr/share/texlive/texmf-dist/tex/latex/currfile/currfile.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/filehook/filehook.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./hello.aux
)
No file pythontex-files-hello/hello.pytxmcr.
Run PythonTeX to create it.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (./hello.aux) )
No pages of output.
Transcript written on hello.log.
Traceback (most recent call last):
  File "/usr/bin/pythontex", line 50, in <module>
    import pythontex2 as pythontex
  File "/usr/share/texlive/texmf-dist/scripts/pythontex/pythontex2.py", line 61, in <module>
    from pygments.styles import get_all_styles
ImportError: No module named pygments.styles
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ 
```

**Comment by ortollj** [comment]
below I put the contents of the file  firstPythonTex.tex:
\begin{pycode}
print(r"\begin{tabular}{c|c}")
print(r"$m$ & $2^m$ \\ \hline")
print(r"%d & %d \\" % (1, 2**1))
print(r"%d & %d \\" % (2, 2**2))
print(r"%d & %d \\" % (3, 2**3))
print(r"%d & %d \\" % (4, 2**4))
print(r"\end{tabular}")\
end{pycode}



```
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ pdflatex firstPythonTex.tex && pythontex firstPythonTex.tex && pdflatex firstPythonTex.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./firstPythonTex.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.

! LaTeX Error: Environment pycode undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 \begin{pycode}
                  
? 

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2 p
     rint(r"\begin{tabular}{c|c}")
? H
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.
? X
No pages of output.
Transcript written on firstPythonTex.log.
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ 

```

**Comment by gpoore** [comment]
@ortollj You had a Pygments import error, so you need to install the `pygments` package for Python.

**Comment by ortollj** [comment]
thank's a lot gpoore, thank's for your patience and time used.
             
```
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ pdflatex hello.tex && pythontex hello.tex && pdflatex hello.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./hello.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pythontex/pythontex.sty
(/usr/share/texlive/texmf-dist/tex/latex/fvextra/fvextra.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
)) (/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lineno/lineno.sty))
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)))) (/usr/share/texlive/texmf-dist/tex/latex/caption/newfloat.sty)
(/usr/share/texlive/texmf-dist/tex/latex/currfile/currfile.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/filehook/filehook.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./hello.aux
)
No file pythontex-files-hello/hello.pytxmcr.
Run PythonTeX to create it.
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (./hello.aux) )
No pages of output.
Transcript written on hello.log.
This is PythonTeX 0.16

--------------------------------------------------
PythonTeX:  hello - 0 error(s), 0 warning(s)

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./hello.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/pythontex/pythontex.sty
(/usr/share/texlive/texmf-dist/tex/latex/fvextra/fvextra.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ifthen.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
)) (/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)
(/usr/share/texlive/texmf-dist/tex/latex/lineno/lineno.sty))
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texlive/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/share/texlive/texmf-dist/tex/latex/pgfopts/pgfopts.sty
(/usr/share/texlive/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
(/usr/share/texlive/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.t
ex)))) (/usr/share/texlive/texmf-dist/tex/latex/caption/newfloat.sty)
(/usr/share/texlive/texmf-dist/tex/latex/currfile/currfile.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/filehook/filehook.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)) (./hello.aux
) (./pythontex-files-hello/hello.pytxmcr)
(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (./pythontex-files-hello/hello.pytxpyg)
(./pythontex-files-hello/py_default_default_0.stdout) [1{/var/lib/texmf/fonts/m
ap/pdftex/updmap/pdftex.map}] (./hello.aux) )</usr/share/texlive/texmf-dist/fon
ts/type1/public/amsfonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type
1/public/amsfonts/cm/cmti10.pfb>
Output written on hello.pdf (1 page, 19432 bytes).
Transcript written on hello.log.
ortollj@ortollj-SATELLITE-C70-B:~/Documents/latex$ 

```

**Comment by ortollj** [comment]
I will try to summarize what I had to do to install and use PythonTex on UBUNTU 18.04.


https://github.com/gpoore/pythontex/issues/133

https://github.com/gpoore/pythontex
you need to download theses two package
https://www.tug.org/texlive/acquire-netinstall.html
install-tl-unx.tar.gz (untar it)
and from 
https://github.com/gpoore/pythontex
click on green button clone or download → Download zip
pythontex-master.zip (unzip it)
############################
https://tex.stackexchange.com/questions/137428/tlmgr-cannot-setup-tlpdb
so
sudo apt-get install xzdec
cd install-tl-20190927/
sudo ./install-tl
(be patient here waiting for about one hour !)
cd Downloads/
cd pythontex-master/

cd pythontex
latex pythontex.ins md ~/texmf md ~/texmf/tex mv * ~/texmf/tex chmod +x ~/texmf/
(I don’t remember why I did the cmd above !)

sudo apt-get install python-pygments

the two files for testing:

export PATH="/usr/local/texlive/2019/bin/x86_64-linux:$PATH"
export PATH="/usr/local/texlive/2019/texmf-dist/doc/man:$MANPATH" export PATH="/export usr/local/texlive/2019/texmf-dist/doc/info:$INFOPATH" 
export PATH="~/Downloads/pythontex-master/pythontex
\documentclass{article}
\usepackage{pythontex}
\begin{document}
\begin{pycode}
print(r'\emph{Hello}, world!')
\end{pycode}
\end{document}


\begin{pycode}
print(r"\begin{tabular}{c|c}")
print(r"$m$ & $2^m$ \\ \hline")
print(r"%d & %d \\" % (1, 2**1))
print(r"%d & %d \\" % (2, 2**2))
print(r"%d & %d \\" % (3, 2**3))
print(r"%d & %d \\" % (4, 2**4))
print(r"\end{tabular}")\
end{pycode}
pdflatex hello.tex && pythontex hello.tex && pdflatex hello.tex
\documentclass{article}
\usepackage{pythontex}
\begin{document}
\begin{pycode}
print(r"\begin{tabular}{c|c}")
print(r"$m$ & $2^m$ \\ \hline")
print(r"%d & %d \\" % (1, 2**1))
print(r"%d & %d \\" % (2, 2**2))
print(r"%d & %d \\" % (3, 2**3))
print(r"%d & %d \\" % (4, 2**4))
print(r"\end{tabular}")\
\end{pycode}
\end{document}


pdflatex firstPythonTex.tex && pythontex firstPythonTex.tex && pdflatex firstPythonTex.tex

but I’m certain I have forgotten something !
