### ISSUE TITLE
ValueError: module functions cannot set METH_CLASS or METH_STATIC

### ISSUE THREAD

**Issue by TheChymera** [gpoore/pythontex#144]
After my last system update I get the following error when importing pandas (or anything which is itself importing pandas) inside pythontex --- but nowhere else: 

```
----  Messages for py:default:default  ----
  Traceback (most recent call last):
* PythonTeX stderr - error on line 6 in "functions.py":
    File "<outputdir>/py_default_default.py", line 71, in <module>
      from lib import boilerplate
    File "/home/chymera/docsrc/RepSeP/lib/boilerplate.py", line 1, in <module>
      import pandas as pd
    File "/usr/lib64/python3.6/site-packages/pandas/__init__.py", line 57, in <module>
      from pandas.io.api import *
    File "/usr/lib64/python3.6/site-packages/pandas/io/api.py", line 19, in <module>
      from pandas.io.packers import read_msgpack, to_msgpack
    File "/usr/lib64/python3.6/site-packages/pandas/io/packers.py", line 69, in <module>
      from pandas.util._move import (
  ValueError: module functions cannot set METH_CLASS or METH_STATIC
```

Can you maybe help me figure out what the issue is?
For a reproducible example try:

```
git@github.com:TheChymera/RepSeP.git
cd RepSeP
./compile.sh
```

If this requires too many deps you do not have, please let me know to start working on a more stripped-down example.

**Comment by gpoore** [comment]
This looks like a pandas bug that was fixed in a more recent release. See https://github.com/pandas-dev/pandas/issues/23040. You can do a search for more details if you need them.

**Comment by TheChymera** [comment]
that seens to have been the case, thank you :)
