### ISSUE TITLE
NameError: name 'WindowsError' is not defined

### ISSUE THREAD

**Issue by mbujosab** [gpoore/pythontex#177]
Can you help me?

This is PythonTeX 0.17
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/share/texlive/texmf-dist/scripts/pythontex/pythontex3.py", line 1560, in run_code
    proc = subprocess.Popen(exec_cmd, stdout=out_file, stderr=err_file)
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/share/texlive/texmf-dist/scripts/pythontex/pythontex3.py", line 1563, in run_code
    except WindowsError as e:
NameError: name 'WindowsError' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/pythontex", line 62, in <module>
    pythontex.main()
  File "/usr/share/texlive/texmf-dist/scripts/pythontex/pythontex3.py", line 2811, in main
    do_multiprocessing(data, temp_data, old_data, engine_dict)
  File "/usr/share/texlive/texmf-dist/scripts/pythontex/pythontex3.py", line 1383, in do_multiprocessing
    result = task.get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'WindowsError' is not defined

**Comment by gpoore** [comment]
Try running `pythontex` with the flag `--interpreter python:python3`. It looks like `python` doesn't exist on the system.

**Comment by mbujosab** [comment]
Thank you! It works fine now.
